test_that("SelfControlledCohort works", {
  unlink(cfg$connectionDetails$server)
  cdmConfig <- loadCdmConfiguration(cdmConfigPath)
  connectionDetails <- Eunomia::getEunomiaConnectionDetails(databaseFile = cfg$connectionDetails$server)
  connection <- DatabaseConnector::connect(connectionDetails)
  importReferenceTables(connection, cdmConfig, referenceZipPath)
  createCohorts(connection, cdmConfig)
  computeSccResults(connection, cdmConfig)
  browser()
  checkmate::expect_file_exists(file.path(cdmConfig$exportPath, paste0("scc-results-", cdmConfig$database, "-aid-1.csv")))
  checkmate::expect_file_exists(file.path(cdmConfig$exportPath, paste0("scc-results-", cdmConfig$database, "-aid-2.csv")))
  checkmate::expect_file_exists(file.path(cdmConfig$exportPath, paste0("scc-results-", cdmConfig$database, "-aid-3.csv")))
  checkmate::expect_file_exists(file.path(cdmConfig$exportPath, paste0("scc-results-", cdmConfig$database, "-aid-4.csv")))
  checkmate::expect_file_exists(file.path(cdmConfig$exportPath, paste0("scc-results-", cdmConfig$database, "-aid-5.csv")))
})